// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		
		int num_of_reps = Integer.parseInt(args[0]);
		double current_score;
		int above_0_5 = 0;
		int below_0_5 = 0;
		double above_0_5_dub = 0.0;
		double below_0_5_dub = 0.0;
		
		for (int i = 0; i < num_of_reps; i++) {
    		
			current_score = Math.random();
			
			if (current_score > 0.5) {
				above_0_5++;
			} else {
				below_0_5++;
			} 
		}
		
		System.out.println("> 0.5: " + above_0_5 + " times");
		System.out.println("<= 0.5: " + below_0_5 + " times");
		
		if (below_0_5 != 0) {
			above_0_5_dub = above_0_5;
			below_0_5_dub = below_0_5;
			System.out.println("Ratio: " + (above_0_5_dub/below_0_5_dub) );
		}
		
		}
}
